# Generated by Django 6.0 on 2025-12-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedGuild',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('guild_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='en', max_length=2)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
