# Generated by Django 6.0 on 2026-01-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='banner',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='guild',
            name='icon',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
